import {build, context} from 'esbuild';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
import {readFile, writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';

const watch = process.argv.includes('--watch');
const options = {
    absWorkingDir: fileURLToPath(new URL('.', import.meta.url)),
    entryPoints: ['src/index.js'],
    outfile: 'base.js',
    bundle: true,
    format: 'iife',
    platform: 'browser',
    target: ['es2018'],
    sourcemap: true,
    minify: false,
    legalComments: 'inline',
    banner: {
        js: '/*! FO Runtime v2 - generated by esbuild; edit src/ instead. | version: 000000 */'
    },
    plugins: [{
        name: 'content-version',
        setup(build) {
            build.onEnd(async result => {
                if (result.errors.length) return;
                const {absWorkingDir, outfile} = build.initialOptions;
                const path = resolve(absWorkingDir, outfile);
                const output = await readFile(path, 'utf8');
                // Hash only the body, avoiding a self-referential banner. Same-width replacement
                // preserves source maps; onEnd runs again after every successful watch rebuild.
                // Exclude the source-map URL too: hashed filenames must not hash themselves.
                const body = output.slice(output.indexOf('\n') + 1).replace(/^\/\/# sourceMappingURL=.*\n?/m, '');
                const version = createHash('sha256').update(body).digest('hex').slice(0, 6);
                const stamped = output.replace('version: 000000', `version: ${version}`);
                await writeFile(path, stamped);
                if (build.initialOptions.minify) {
                    const name = `base.min.${version}.js`;
                    const map = JSON.parse(await readFile(path + '.map', 'utf8'));
                    map.file = name;
                    await writeFile(resolve(absWorkingDir, name + '.map'), JSON.stringify(map));
                    await writeFile(resolve(absWorkingDir, name), stamped.replace(
                        /^\/\/# sourceMappingURL=.*$/m, `//# sourceMappingURL=${name}.map`));
                    console.log(`Built ${name} and ${name}.map`);
                }
                console.log(`${outfile}: version ${version}`);
            });
        }
    }]
};

const builds = [
    options,
    {...options, outfile: 'base.min.js', minify: true}
];

if (watch) {
    const contexts = await Promise.all(builds.map(settings => context(settings)));
    await Promise.all(contexts.map(buildContext => buildContext.watch()));
    console.log('Watching js/src ...');
} else {
    await Promise.all(builds.map(settings => build(settings)));
    console.log('Built js/base.js and js/base.min.js (with source maps)');
}
