import {build, context} from 'esbuild';
import {fileURLToPath} from 'node:url';

const watch = process.argv.includes('--watch');
const options = {
    absWorkingDir: fileURLToPath(new URL('.', import.meta.url)),
    entryPoints: ['src/index.js'],
    outfile: 'base.js',
    bundle: true,
    format: 'iife',
    platform: 'browser',
    target: ['es2018'],
    sourcemap: true,
    minify: false,
    legalComments: 'inline',
    banner: {
        js: '/*! FO Runtime v2 - generated by esbuild; edit src/ instead. */'
    }
};

const builds = [
    options,
    {...options, outfile: 'base.min.js', minify: true}
];

if (watch) {
    const contexts = await Promise.all(builds.map(settings => context(settings)));
    await Promise.all(contexts.map(buildContext => buildContext.watch()));
    console.log('Watching js/src ...');
} else {
    await Promise.all(builds.map(settings => build(settings)));
    console.log('Built js/base.js and js/base.min.js (with source maps)');
}
